package com.chabed.hibernate.pojo;
// Generated Mar 15, 2017 3:30:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * T30004 generated by hbm2java
 */
public class T30004  implements java.io.Serializable {


     private String TGenCode;
     private String TEntryUser;
     private Date TEntryDate;
     private String TUpdUser;
     private Date TUpdDate;
     private String TLang1Name;
     private String TLang2Nam;
     private String TDrugTherapClsCode;
     private String TActiveFlag;
     private String TControlDrug;
     private String TDrugUse;

    public T30004() {
    }

	
    public T30004(String TGenCode) {
        this.TGenCode = TGenCode;
    }
    public T30004(String TGenCode, String TEntryUser, Date TEntryDate, String TUpdUser, Date TUpdDate, String TLang1Name, String TLang2Nam, String TDrugTherapClsCode, String TActiveFlag, String TControlDrug, String TDrugUse) {
       this.TGenCode = TGenCode;
       this.TEntryUser = TEntryUser;
       this.TEntryDate = TEntryDate;
       this.TUpdUser = TUpdUser;
       this.TUpdDate = TUpdDate;
       this.TLang1Name = TLang1Name;
       this.TLang2Nam = TLang2Nam;
       this.TDrugTherapClsCode = TDrugTherapClsCode;
       this.TActiveFlag = TActiveFlag;
       this.TControlDrug = TControlDrug;
       this.TDrugUse = TDrugUse;
    }
   
    public String getTGenCode() {
        return this.TGenCode;
    }
    
    public void setTGenCode(String TGenCode) {
        this.TGenCode = TGenCode;
    }
    public String getTEntryUser() {
        return this.TEntryUser;
    }
    
    public void setTEntryUser(String TEntryUser) {
        this.TEntryUser = TEntryUser;
    }
    public Date getTEntryDate() {
        return this.TEntryDate;
    }
    
    public void setTEntryDate(Date TEntryDate) {
        this.TEntryDate = TEntryDate;
    }
    public String getTUpdUser() {
        return this.TUpdUser;
    }
    
    public void setTUpdUser(String TUpdUser) {
        this.TUpdUser = TUpdUser;
    }
    public Date getTUpdDate() {
        return this.TUpdDate;
    }
    
    public void setTUpdDate(Date TUpdDate) {
        this.TUpdDate = TUpdDate;
    }
    public String getTLang1Name() {
        return this.TLang1Name;
    }
    
    public void setTLang1Name(String TLang1Name) {
        this.TLang1Name = TLang1Name;
    }
    public String getTLang2Nam() {
        return this.TLang2Nam;
    }
    
    public void setTLang2Nam(String TLang2Nam) {
        this.TLang2Nam = TLang2Nam;
    }
    public String getTDrugTherapClsCode() {
        return this.TDrugTherapClsCode;
    }
    
    public void setTDrugTherapClsCode(String TDrugTherapClsCode) {
        this.TDrugTherapClsCode = TDrugTherapClsCode;
    }
    public String getTActiveFlag() {
        return this.TActiveFlag;
    }
    
    public void setTActiveFlag(String TActiveFlag) {
        this.TActiveFlag = TActiveFlag;
    }
    public String getTControlDrug() {
        return this.TControlDrug;
    }
    
    public void setTControlDrug(String TControlDrug) {
        this.TControlDrug = TControlDrug;
    }
    public String getTDrugUse() {
        return this.TDrugUse;
    }
    
    public void setTDrugUse(String TDrugUse) {
        this.TDrugUse = TDrugUse;
    }




}


